# Generated by Django 3.2.7 on 2021-09-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=191)),
                ('name', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('date_edited', models.DateTimeField()),
                ('public', models.BooleanField()),
                ('favorite', models.BooleanField()),
                ('views', models.IntegerField()),
            ],
        ),
    ]
