# Generated by Django 3.2.7 on 2021-09-11 14:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_competed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
