# Generated by Django 3.2.7 on 2021-09-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20210911_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='liked_users',
            field=models.TextField(default=''),
        ),
    ]
