# Generated by Django 3.2.7 on 2021-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_note_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='date_edited',
            field=models.DateTimeField(blank=True),
        ),
    ]
