# Generated by Django 3.2.7 on 2021-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20210913_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
