# Generated by Django 3.2.7 on 2021-09-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_alter_note_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='likes',
        ),
    ]
